spring:
  application:
    name: depart-provider  # 应用程序名称
  profiles:
    active: dev  # 激活的配置文件，这里是 dev 配置文件
  config:
    # 从 Nacos 导入配置文件。配置文件名默认为 application，这里指定了 depart-provider-dev.yaml
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      config:
        server-addr: nacos-local:8848  # Nacos 配置中心的服务器地址
        file-extension: yaml  # 配置文件的扩展名，默认为 yaml
        username: nacos  # 访问 Nacos 配置中心的用户名
        password: nacos  # 访问 Nacos 配置中心的密码
        group: DEFAULT_GROUP  # 配置文件的分组, 默认为 DEFAULT_GROUP
