server:
  port: 8080

spring:
  application:
    name: business-service # 微服务名称
  cloud:
    nacos:
      discovery:
        server-addr: nacos-local:8848 # nacos注册中心地址
        username: nacos # 用户名密码
        password: nacos
        group: SEATA_GROUP
seata:
  enabled: true # 是否开启spring-boot自动装配，默认为true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-tx-group
  service:
    vgroup-mapping:
      business-service-tx-group: default  # seata默认的集群名称，注意名字要和tx-service-group的值一致才行
  registry:
    type: nacos
    nacos:
      server-addr: nacos-local:8848
      namespace:
      username: nacos
      password: nacos
      cluster: default
      application: seata-server
      group: SEATA_GROUP
