server:
  port: 8080

spring:
  application:
    name: depart-consumer # 微服务名称
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848 # nacos注册中心地址
        username: # 用户名密码
        password: